#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[[ -f $sysresources ]] && xrdb -merge $sysresources
[[ -f $sysmodmap ]] && xmodmap $sysmodmap
# merge in xresources and keymaps
[[ -f $userresources ]] && xrdb -merge $userresources
[[ -f $usermodmap ]] && xmodmap $usermodmap

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# start scripts
sort_download_dir &
#transmission_auto_download &

# start background application
flameshot &
/usr/lib/kdeconnectd &
mpd &
mpDris2 &
nitrogen --restore &
pcmanfm -d &
#picom &
syncthing --no-browser &
setxkbmap -layout 'us,us,us' -variant 'dvp,dvorak,' && sxhkd &
transmission-daemon &

# start WM
exec dwm
