#!/bin/sh

# merge in xresources and keymaps
[[ -f $userresources ]] && xrdb -merge $XDG_CONFIG_HOME/X11/Xresources
[[ -f $usermodmap ]] && xmodmap $usermodmap

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# start scripts
sort_download_dir &
remap && sxhkd &

# start background application
dwmblocks &
flameshot &
/usr/lib/kdeconnectd &
mpd &
mpDris2 &
nitrogen --restore &
pcmanfm -d &
syncthing --no-browser &
transmission-daemon &
unclutter &

# start WM
exec dwm
