#!/bin/sh

xrdb -merge $XDG_CONFIG_HOME/X11/Xresources

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# as root
doas darkstat -i enp1s0 -p 669 &
doas darkstat -i wlp2s0 -p 667 &

# start scripts
sort_download_dir &
remap && sxhkd &

# start background application
dwmblocks &
flameshot &
/usr/lib/kdeconnectd &
mpd &
mpDris2 &
nitrogen --restore &
pcmanfm -d &
syncthing --no-browser &
transmission-daemon &
transmission-rss &
unclutter --timeout 3 --ignore-scrolling &

# start WM
exec dwm
