#!/bin/sh

if [[ -n $(xrandr | rg 'HDMI-1 connected') ]]; then
    #autorandr dual-vert
    #xrandr --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --output LVDS1 --mode 1366x768 --pos 277x1080
    xrandr --output HDMI-1 --primary --mode 1920x1080 --output LVDS-1 --off
else
	#autorandr laptop
    xrandr --output LVDS-1 --primary --auto --output HDMI-1 --off
fi

nitrogen --restore
