############
# starship #
############

# format = '''$jobs$shell$memory_usage$hostname$username$directory$status$character'''
# right_format = '''$all'''

add_newline = false

# [line_break]
# disabled = true

[character]
success_symbol = '[](bold green)' # nf-fa-chevron_right
error_symbol = '[](bold red)'     # nf-fa-chevron_up
vicmd_symbol = '[](bold purple)'  # nf-fa-chevron_left

[cmd_duration]
format = '[ $duration]($style)'
show_notifications = true
notification_timeout = 2_000

[directory]
format = '[$read_only]($read_only_style)[$path]($style) '
read_only = ' ' # nf-fa-lock
read_only_style = 'bold red'
before_repo_root_style = 'grey'
repo_root_style = 'green'
repo_root_format = '[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style) '
fish_style_pwd_dir_length = 1

[jobs]
symbol = '✦'

[shell]
disabled = false
zsh_indicator = ''

[shlvl]
threshold = 3
format = '[$symbol$shlvl]($style) '
symbol = ''
# disabled = false

[status]
map_symbol = true
pipestatus = true
disabled = false

[time]
format = '[$time]($style) '
time_format = '%H:%M'
disabled = false

##########
# system #
##########

[battery]
full_symbol = '󱊣 '
charging_symbol = '󱊥 '
discharging_symbol = '󱊡 '
unknown_symbol = '󱃍 '
empty_symbol = '󰂎 '
[[battery.display]]
threshold = 10
style = 'bold red'
[[battery.display]]
threshold = 20
style = 'bold yellow'
[[battery.display]]
threshold = 30
style = 'bold'

[hostname]
format = '[$hostname]($style) '

[memory_usage]
disabled = false
symbol = '󰍛'
format = '$symbol [${ram_pct}|(${swap_pct})]($style) '

[username]
format = '[$user]($style)@'

###############
# development #
###############

[c]
symbol = '' # nf-custom-c

[dart]
format = '[$symbol($version )]($style)'
symbol = '' # nf-dev-dart

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = '' # nf-dev-git_branch

[golang]
symbol = '' # nf-dev-go

[haskell]
symbol = '' # nf-dev-haskell

[java]
symbol = '' # nf-dev-java

[kotlin]
symbol = '' # nf-custom-kotlin

[lua]
symbol = '󰢱'

[nodejs]
format = '[$symbol($version )]($style)'
symbol = '' # nf-dev-nodejs_small

[package]
format = '[$symbol$version]($style) '
symbol = ' ' # nf-cod-package
# symbol = '' # nf-dev-code

[php]
symbol = ''

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = '${raw}'
symbol = '' # nf-dev-python
# pyenv_version_name = true
# pyenv_prefix = ' ' # nf-cod-server_environment

[ruby]
symbol = '' # nf-dev-ruby

[rust]
symbol = '' # nf-dev-rust
