#!/bin/bash

title=$(playerctl metadata title)
artist=" -  $(playerctl metadata artist)"
state=$(playerctl status)

if [ "$state" = "Playing" ]; then
    icon=">> "
elif [ "$state" = "Paused" ]; then
    icon="|| "
else
    icon=""
    title=""
    artist=""
fi

echo $icon $title $artist
